steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - functions
    - deploy
    - -runtime=go113
    - -trigger-http
    - -source=./ # Function source files
    - -entry-point=HelloWorld # Function entry point
    - helloWorld # Function name
 waitFor: ['_']
 id: 'hello-world'