steps:
- name: 'gcr.io/piccolo-287818/piccolo-function-builder:0.1'
  args: ['make', 'test']
  id: 'test'
# TODO Replace with terraform
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'make'
  args:
    - function-population-generate
  waitFor: ['test']
  id: 'populationgenerate'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'make'
  args:
    - function-roster-import
  waitFor: ['test']
  id: 'rosterimport'