steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - functions
    - deploy
    - --runtime=go113
    - --trigger-http
    - --source=./functions/helloworld # Function source files
    - --entry-point=HelloWorld # Function entry point
    - --region=europe-west1
    - helloWorld # Function name
  waitFor: ['-']
  id: 'hello-world'