steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - beta 
      - builds 
      - triggers 
      - import 
      - --source=functions/helloworld/build/trigger
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - beta 
      - builds 
      - triggers 
      - import 
      - --source=functions/goodbye/build/trigger
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - beta 
      - builds 
      - triggers 
      - import 
      - --source=functions/genetic/build/trigger
