steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cloud beta builds triggers create github helloworld --included-files "functions/helloworld/*" --repo-name=piccolo --repo-owner=nlamot --branch-pattern="^master$"