steps:
- name: 'registry.hub.docker.com/library/golang:1.13'
  args: ['make', 'test']
  id: 'test'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'make'
  args:
    - function-population-generate
  waitFor: ['test']
  id: 'populationgenerate'
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - mb
    - gs://rosters
  waitFor: ['-']
  id: 'createrostersbucket'k
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'make'
  args:
    - function-roster-import
  waitFor: ['createrostersbucket','test']
  id: 'rosterimport'