steps:
- name: 'registry.hub.docker.com/library/golang:1.13'
  args: ['make', 'test']
  id: 'test'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - functions
    - deploy
    - --runtime=go113
    - --trigger-http
    - --source=.
    - --entry-point=GeneratePopulation # Function entry point
    - --region=europe-west1
    - --allow-unauthenticated # This function is publicly available 
    - generatepopulation # Function name
  waitFor: ['test']
  id: 'deployfunction'