steps:
# Configure the Hello World cloud function
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - functions
    - add-iam-policy-binding
    - --member="allUsers"
    - --role="roles/cloudfunctions.invoker"
    - helloWorld # Function name
  waitFor: ['-']
  id: 'hello-world-access'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - functions
    - deploy
    - --runtime=go113
    - --trigger-http
    - --source=./functions/helloworld # Function source files
    - --entry-point=HelloWorld # Function entry point
    - --region=europe-west1
    - --allow-unauthenticated # This function is publicly available 
    - helloWorld # Function name
  waitFor: ['hello-world-access']
  id: 'hello-world'