steps:
- name: 'registry.hub.docker.com/library/golang:1.13'
  args: ['make', 'test']
  id: 'test'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'make'
  args:
    - function-generate-population
  waitFor: ['test']
  id: 'deployfunction'