// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DocumentRef is an autogenerated mock type for the DocumentRef type
type DocumentRef struct {
	mock.Mock
}

// ID provides a mock function with given fields:
func (_m *DocumentRef) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
