// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gcp "piccolo.com/planner/pkg/common/gcp"
)

// FirestoreClient is an autogenerated mock type for the FirestoreClient type
type FirestoreClient struct {
	mock.Mock
}

// Collection provides a mock function with given fields: _a0
func (_m *FirestoreClient) Collection(_a0 string) gcp.CollectionRef {
	ret := _m.Called(_a0)

	var r0 gcp.CollectionRef
	if rf, ok := ret.Get(0).(func(string) gcp.CollectionRef); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gcp.CollectionRef)
		}
	}

	return r0
}
