// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	population "piccolo.com/planner/pkg/genetic/population"
)

// PopulationService is an autogenerated mock type for the PopulationService type
type PopulationService struct {
	mock.Mock
}

// Generate provides a mock function with given fields: _a0
func (_m *PopulationService) Generate(_a0 population.GeneratePopulationRequest) {
	_m.Called(_a0)
}
