// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PopulationRepository is an autogenerated mock type for the PopulationRepository type
type PopulationRepository struct {
	mock.Mock
}
