// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// PopulationController is an autogenerated mock type for the PopulationController type
type PopulationController struct {
	mock.Mock
}

// Generate provides a mock function with given fields: _a0, _a1
func (_m *PopulationController) Generate(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}
