// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	csv "encoding/csv"

	mock "github.com/stretchr/testify/mock"
	roster "piccolo.com/planner/pkg/planning/roster"
)

// RosterManager is an autogenerated mock type for the RosterManager type
type RosterManager struct {
	mock.Mock
}

// ImportCSV provides a mock function with given fields: _a0
func (_m *RosterManager) ImportCSV(_a0 *csv.Reader) (roster.Roster, error) {
	ret := _m.Called(_a0)

	var r0 roster.Roster
	if rf, ok := ret.Get(0).(func(*csv.Reader) roster.Roster); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(roster.Roster)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*csv.Reader) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
