// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	roster "piccolo.com/planner/pkg/planning/roster"
)

// RosterRepository is an autogenerated mock type for the RosterRepository type
type RosterRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *RosterRepository) Create(_a0 string, _a1 roster.Roster) (string, error) {
	ret := _m.Called(_a0, _a1)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, roster.Roster) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, roster.Roster) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
