// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WriteResult is an autogenerated mock type for the WriteResult type
type WriteResult struct {
	mock.Mock
}
