steps:
# Configure the Hello World cloud function
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - functions
    - deploy
    - --runtime=go113
    - --trigger-http
    - --entry-point=HelloWorld # Function entry point
    - --region=europe-west1
    - --allow-unauthenticated # This function is publicly available 
    - helloWorld # Function name
  waitFor: ['-']
  id: 'hello-world'